// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI (migrate/validate/studio/db execute) uses this URL directly.
    // Prefer the unpooled/direct connection here -- migrations run DDL and can be
    // unreliable through a transaction-mode pooler (e.g. Neon's "-pooler" host).
    // The running app does NOT read this file; it instantiates PrismaClient with
    // its own driver adapter (e.g. new PrismaPg({ connectionString: DATABASE_URL })),
    // so app runtime queries go through the pooled DATABASE_URL as usual.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
